<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
		<AssemblyName>Task</AssemblyName>
		<OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <SelfContained>true</SelfContained>
        <PublishSingleFile>true</PublishSingleFile>
        <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
        <PublishReadyToRun>true</PublishReadyToRun>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.1"/>
    </ItemGroup>

</Project>
